# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: wwiRWuG8LyZ3c0fskJ6lsHn6HwHmtAg3
            client-secret: V2k0Kg6YxQdK0rPRzr3_ei0V4BwGehVYDFiC64G0TsbaACqGjYXGfmKnafOvSFKs
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-0jb5xq75.us.auth0.com/